### PR TITLE
Decouples authorization/refresh req/res from setting the auth token.

### PR DESCRIPTION
**Pull request by AndrewZurn**
Fix for option 2 of #20 

Previously a client couldn't fully override the authorize method without losing some essential functionality, as they didn't have access to either the setAuth method or the sync var storing the auth token. Now clients can fully override these methods and let the `RedoxClient`'s private/protected methods handle setting the new auth token in it's sync var and scheduling the new refresh.

### CODE REVIEW

**Comment by AndrewZurn** [comment]
@apatzer A little bit more of an involved PR, if your interested or have comments/concerns, let me know.

**Comment by apatzer** [comment]
@AndrewZurn These look solid, and easy to understand. Thanks for another contribution!

**Comment by apatzer** [comment]
Released to the public as v0.92 to Sonatype.

**Comment by AndrewZurn** [comment]
Thanks for the opportunity!

**Pull request merged**
